name: tin_portfolio
description: "own portforlio project"


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.9.0
  universal_html: ^2.2.4
  http: ^1.3.0
  google_fonts: ^6.3.2
  device_frame_plus: ^1.5.0
  animated_text_kit: ^4.2.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true



  assets:
    - assets/
    - assets/images/
